### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by moenasrallah**
* had lfs issues with the latest version. Adding 'git lfs clone' instead of 'git clone' solved some lfs issues.
* added clarification for running the build command to clarify that you need to be cd'ed into the repository itself first.

### CODE REVIEW

**Comment by moenasrallah** [comment]
Also, it would be awesome if you guys made a Discord server to speak to you! 
Me and my colleagues would like to be in contact with your team and offer resources/collaboration. 
Can't find emails or any contact info :-(

**Comment by moenasrallah** [comment]
Thank you for the response. You are correct about the deprecation. I relied on Atlassian's site for information when looking for a solution for the issue I posted this week:

https://github.com/lgsvl/simulator/issues/16
https://www.atlassian.com/git/tutorials/git-lfs

"Once Git LFS is installed, you can clone a Git LFS repository as normal using git clone."

"If you're cloning a repository with a large number of LFS files, the explicit git lfs clone command offers far better performance"

My problem was that some of the large assets were not downloaded even when I had the latest lfs installed. It seemed that git lfs clone helped fix my issue and everything is good now.  Maybe it was just a hiccup specific to my set up... but if anyone else encounters this issue, it would be nice to note in a troubleshooting section.

**Comment by martins-mozeiko** [comment]
If you have done `git lfs install` once then it installs special hook ("smudge") that makes clone/pull/push commands to automatically download/upload LFS objects by default unless you explicitly override it. So there is no need to do git lfs clone.

To speed up git clones ourselves we do following command first time:

    GIT_LFS_SKIP_SMUDGE=1 git clone https://url/of/simulator.git
    cd simulator && git lfs fetch && git lfs checkout

First command downloads regular git objects and skips LFS objects, second one downloads & checks out LFS objects.

After that, next time "git pull" works reasonably fast as it downloads only newer changes, and there there is no need for workarounds.

**Comment by moenasrallah** [comment]
Awesome. Thanks for the reply and explanation. Makes better sense

**Pull request closed without merging**
