### PR TITLE
Added Instance Segmentation Sensor type

### PR DESCRIPTION
**Pull request by KonstantinKohl**
Based on Semantic Segmentation Sensor, created Instance Segmentation Sensor type. Assigns random color to object instances of specific categories (eg cars, pedestrians etc.). For users working with downloaded content, this will work only partially because in the downloaded content, the new shader pass isn't known, resulting in only objects rendering that have their materials outside the downloaded packages (this is true for AI vehicles and pedestrians). Once LG takes this change and rebuilds their content, this will be fixed.

### CODE REVIEW

**Comment by martins-mozeiko** [comment]
I'm not sure change on line 318 in SimulatorManager.cs from GetSharedMaterials to GetMaterials is a good idea.

The way how Unity renders is by batching - if multiple objects use same material instance they will be rendered with one drawcall. By making each material unique between similar objects your change prevents doing this. Unity needs to issue separate draw calls, because each object will have unique material.

Having drawcall per instance, not per material is a significant performance hit. On my machine for BorregasAve it drops performance from ~60 to 40 fps (with some sensors on the car). Without any sensors performance drops from 150 to 100 fps.

I'll think about how this can be changed. I understand that materials need to be different because each has different color assigned. Not sure how to change it. Technically Unity should be able to put this in instance specific constant buffer, but I don't know HDRP implementation details to explain how exactly this should be done. I think currently LitProperties.hlsl define properties only per material - `CBUFFER_START(UnityPerMaterial)` Per instance properties probably are somewhere else.

**Comment by KonstantinKohl** [comment]
@martins-mozeiko I wasn't aware of this implication, thanks for the heads-up.

Thinking of it, I will go on and change the code such that only for objects that ask for instance segmentation (AllowInstanceSegmentation), I will make the materials unique and keep the original code in place for the rest. In our case, only few objects will need instance segmentation (cars, pedestrians, traffic signs and traffic lights), while the majority of the world won't, so I trade a bit of performance against making the system work for us.

I'll submit my changes to this branch so your team can decide if this works for you.

**Comment by RamoramaInteractive** [comment]
I want to have Instance Segmentation Sensor type. I know, the performance of the simulator would be very low. What should I change to enable the Instance Segmentation Sensor type?

**Comment by rongguodong** [comment]
We will support instance segmentation soon.

**Comment by EricBoiseLGSVL** [comment]
@KonstantinKohl We had to make some major changes to make this work in simulator.  I am closing this but your work is merged in the feature.  Thank you for your hard work and this feature is now released.  The segmentation camera has parameters to enable this for each tag type.

**Pull request closed without merging**
